parameters:
  - name: JOB_VARIANT
    type: string
    default: ""

jobs:
  - job: Complete${{ parameters.JOB_VARIANT }}
    timeoutInMinutes: 40
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - template: setup.yml
        parameters:
          JOB_VARIANT: ${{ parameters.JOB_VARIANT }}

      - script: |
          set -ex
          cd tests/fixtures/complete/
          derex mysql reset --force
          derex reset-rabbitmq
          derex create-bucket
          derex ecommerce reset-mysql
          derex ecommerce load-fixtures
          derex discovery reset-mysql
          derex discovery load-fixtures
          derex discovery create-index
        displayName: "Prime Mysql and Elasticsearch"

      - script: |
          set -ex
          cd tests/fixtures/complete/
          derex runmode production
          ddc-project config
          ddc-project up -d lms cms ecommerce discovery
        displayName: "Start lms, cms, ecommerce and discovery"

      - script: |
          set -ex
          cd tests/fixtures/complete/
          ddc-project logs
        displayName: "Show logs"

      - script: |
          set -ex
          COUNT=$(
            curl -sf http://discovery.discovery-complete.localhost/health/ \
              --connect-timeout 30 \
              --retry 5 \
              --retry-delay 5 \
              --retry-connrefused | grep -o "OK" | wc -l
          )
          if [ $COUNT != 2 ]; then
              exit 1
          fi
        displayName: "Curl the Discovery service"

      - script: |
          set -ex
          cd tests/fixtures/complete/
          derex discovery refresh-course-metadata
          derex discovery update-index
        displayName: "Run Discovery data synchronization pipeline"
