parameters:
  - name: JOB_VARIANT
    type: string
    default: ""

jobs:
  - job: Minimal${{ parameters.JOB_VARIANT }}
    timeoutInMinutes: 40
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - template: setup.yml
        parameters:
          JOB_VARIANT: ${{ parameters.JOB_VARIANT }}

      - script: |
          set -ex
          cd tests/fixtures/minimal/
          derex mysql reset --force
          derex discovery reset-mysql
          derex discovery load-fixtures
          derex discovery create-index
        displayName: "Prime Mysql and Elasticsearch"

      - script: |
          set -ex
          cd tests/fixtures/minimal/
          derex runmode production
          ddc-project config
          ddc-project up -d lms cms discovery
        displayName: "Start lms, cms and discovery"

      - script: |
          set -ex
          cd tests/fixtures/minimal/
          ddc-project logs
        displayName: "Show logs"


      - script: |
          set -ex
          curl -f http://discovery.discovery-minimal.localhost/health/ \
            --connect-timeout 30 \
            --retry 5 \
            --retry-delay 5 \
            --retry-connrefused
          [ "$(curl -f http://discovery.discovery-minimal.localhost/health/ | jq '.overall_status')" == '"OK"' ]
        displayName: "Curl the Discovery service"

      - script: |
          set -ex
          cd tests/fixtures/minimal/
          derex discovery refresh-course-metadata
          derex discovery update-index
        displayName: "Run Discovery data synchronization pipeline"
