steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
    displayName: 'Use Python 3.7'

  - script: |
      set -ex
      sudo mkdir /etc/derex/
      echo ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ | sudo tee /etc/derex/main_secret
      pip3 install -U pip setuptools
      [ "${{ parameters.JOB_VARIANT }}" == "Pinned" ] && pip3 install -r requirements_dev.txt .
      [ "${{ parameters.JOB_VARIANT }}" == "UnPinned" ] && pip3 install . \
        https://github.com/Abstract-Tech/derex.runner/tarball/master#egg=derex.runner \
        https://github.com/Abstract-Tech/derex.ecommerce/tarball/master#egg=derex.ecommerce
      true
    displayName: 'Install derex.runner'

  - script: ddc-services up -d
    displayName: "Start services"
