steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
    displayName: 'Use Python 3.7'

  - script: |
      set -ex
      pip3 install -U pip setuptools
      [ -z "${{ parameters.PIN_VERSIONS }}" ] && pip3 install -r requirements_dev.txt .
      [ ! -z "${{ parameters.PIN_VERSIONS }}" ] && pip3 install . \
        https://github.com/Abstract-Tech/derex.runner/tarball/master#egg=derex.runner \
        https://github.com/Abstract-Tech/derex.ecommerce/tarball/master#egg=derex.ecommerce
      true
    displayName: 'Install derex.runner'

  - script: ddc-services up -d
    displayName: "Start services"
