parameters:
  - name: JOB_VARIANT
    type: string

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.8"
    displayName: "Use Python 3.8"

  - script: |
      set -x
      # Add hostname entry to /etc/hosts (should be already present but is not)
      echo 127.0.0.1 $(hostname) | sudo tee -a /etc/hosts
      # Disable systemd resolver
      sudo systemctl disable systemd-resolved
      sudo systemctl stop systemd-resolved
      # Configure Cloudlflare DNS resolver
      sudo rm /etc/resolv.conf
      echo "nameserver 1.1.1.1" | sudo tee /etc/resolv.conf
      # Install and configure dnsmasq
      sudo apt-get install dnsmasq
      echo -e "address=/localhost/127.0.0.1\nport=53\ndomain-needed\nlisten-address=127.0.0.53" | sudo tee /etc/dnsmasq.conf
      echo "nameserver 127.0.0.53" | sudo tee /etc/resolv.conf
      echo "nameserver 1.1.1.1" | sudo tee -a /etc/resolv.conf
      sudo systemctl enable dnsmasq
      sudo systemctl restart dnsmasq
      # Resolve docker registry and foobar.localhost hostnames to make sure everything works
      dig registry-1.docker.io @127.0.0.53 && dig foobar.localhost @127.0.0.53 && getent hosts foobar.localhost discovery-minimal.localhost discovery.discovery-minimal.localhost discovery.discovery-complete.localhost foo.bar.localhost registry-1.docker.io
    displayName: "Install dnsmasq to make *.localhost work"

  - script: |
      set -ex
      sudo mkdir /etc/derex/
      echo ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ | sudo tee /etc/derex/main_secret
      pip3 install -U pip setuptools
      { [ "${{ parameters.JOB_VARIANT }}" == "Pinned" ] && pip3 install -r requirements.txt . || true; }
      { [ "${{ parameters.JOB_VARIANT }}" == "UnPinned" ] && pip3 install . \
        https://github.com/Abstract-Tech/derex.runner/tarball/master#egg=derex.runner \
        https://github.com/Abstract-Tech/derex.ecommerce/tarball/master#egg=derex.ecommerce || true; }
    displayName: "Install derex.discovery"

  - script: ddc-services up -d
    displayName: "Start services"
